vsv: synchronize with upstream

diff --git a/files/usr/local/bin/vsv b/files/usr/local/bin/vsv
--- a/files/usr/local/bin/vsv
+++ b/files/usr/local/bin/vsv
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 #
-# Void Liunx service manager (runit)
+# Void Linux service manager (runit)
 #
 # Author: Dave Eddy <dave@daveeddy.com>
 # Date: August 29, 2018
 # License: MIT
 
-VSV_VERSION='v1.2.1'
+VSV_VERSION='v1.3.4'
 
 export SVDIR=${SVDIR:-/var/service}
 export SVCFG=${SVCFG:-/etc/sv}
@@ -55,18 +55,26 @@ human() {
 # setcolors on   # colors on
 # setcolors off  # colors off
 # setcolors auto # colors on or off depending on environment
-_colorsSet=false
 setcolors() {
 	local opt=$1
+	local colors
 
-	# determine if colors should be enabled or not
 	if [[ $opt == auto ]]; then
-		# if stdout is a TTY and the TERM looks like it supports color
-		# enable colors
-		if [[ -t 1 && $TERM == *color* ]]; then
-			opt='on'
-		else
+		# no colors if stdout is not a TTY
+		if [[ ! -t 1 ]]; then
 			opt='off'
+		else
+			# stdout is a tty, check tput capability for colors
+			colors=$(tput colors 2>/dev/null || echo -1)
+			if ! [[ $colors =~ $num_re ]]; then
+				fatal "failed to parse output of \`tput colors\` ($colors)"
+			fi
+
+			if ((colors >= 8)); then
+				opt='on'
+			else
+				opt='off'
+			fi
 		fi
 	fi
 
@@ -99,7 +107,6 @@ setcolors() {
 			exit 1
 			;;
 	esac
-	_colorsSet=true
 }
 
 usage() {
@@ -135,12 +142,22 @@ ${colorgreen}-V                       $cr Print the version number and exit
 ${coloryellow}ENV:${colorgreen}
 SVDIR                    $cr The directory to use, passed to the 'sv' command, can
                           be overridden with '-d <dir>'
+${colorgreen}
+SVCFG                    $cr The directory containing available services
 
 ${coloryellow}SUBCOMMANDS:${colorgreen}
 status [-lt] [filter]    $cr Default subcommand, show process status
 			 $cr '-t' enables tree mode (process tree)
 			 $cr '-l' enables log mode (show log processes)
 			 $cr 'filter' is an optional string to match service names against
+${colorgreen}
+enable <svc> [...]       $cr Enable the service(s) (remove the "down" file, does not start service)
+${colorgreen}
+disable <svc> [...]      $cr Disable the service(s) (create the "down" file, does not stop service)
+${colorgreen}
+link <svc> [...]         $cr Link the service(s) (create symbolic link to $SVDIR)
+${colorgreen}
+unlink <svc> [...]       $cr Unlink the service(s) (remove symbolic link from $SVDIR)
 
 Any other subcommand gets passed directly to the 'sv' command, see sv(1) for the
 full list of subcommands and information about what each does specifically.
@@ -213,12 +230,18 @@ rmsg() {
 	echo "$logo" "$statuscolor$*$colorreset"
 }
 
+disable_message() {
+	local svc=$1
+
+	echo "service $svc disabled by user $USER on $(date)"
+}
+
 # process the status of a single service
 process_service() {
 	local svc=$1
 	local now=$2
 	local pid when up msg char err enabled msgcolor enabledcolor \
-	    statecolor code islog prog
+	    statecolor code islog prog down
 
 	islog=false
 	if [[ $svc == */log ]]; then
@@ -239,7 +262,8 @@ process_service() {
 		msg=$(human "$up")
 
 		# if the service is enabled (wants up or wants down)
-		if [[ -e $svc/down ]]; then
+		if down=$(cat "$svc/down" 2>&1); then
+			verbose "service disabled: $down"
 			enabled='false'
 		else
 			enabled='true'
@@ -300,6 +324,8 @@ process_service() {
 	# figure out program name
 	if [[ -n $pid ]]; then
 		IFS= read -d $'\0' -r prog _ < /proc/$pid/cmdline
+		prog=${prog##*/}
+		prog=${prog:0:17}
 	fi
 
 	# print service line
@@ -406,36 +432,104 @@ do_status() {
 	echo
 }
 
-# handle the disable subcommand
-do_disable() {
+# handle the enable and disable subcommands
+do_enable_disable() {
+	local cmd=$1
+	local svc
+	local ret=0
+	local file
+	shift
+
 	if (($# < 1)); then
-		rmsg -1 "Argument expected for 'sv disable'"
+		rmsg -1 "Argument expected for '$cmd'"
 		return 1
 	fi
 
+	# Loop all arguments as services
+	msg "Running $progname $cmd $*"
+
 	for svc in "$@"; do
-		cmd="rm -f $SVDIR/$svc"
-		msg "Running $cmd"
-		$cmd
-		local ret=$?
-		rmsg "$ret" "[$cmd], exit code: $ret"
+		# Validate service name
+		if ! [[ $svc =~ $svc_re ]]; then
+			rmsg -1 "unexpected characters in name: '$svc'" >&2
+			continue
+		fi
+
+		# ensure service exists
+		if ! [[ -d $svc ]]; then
+			rmsg -1 "service directory '$svc' does not exist" >&2
+			continue
+		fi
+
+		file=$svc/down
+
+		case "$cmd" in
+			enable)
+				verbose "enable '$svc': rm -f '$file'"
+				if ! rm -f "$file"; then
+					rmsg 1 "failed to enable '$svc'"
+					ret=1
+				fi
+				;;
+			disable)
+				verbose "disabling '$svc': creating '$file'"
+				if ! disable_message "$svc" > "$file"; then
+					rmsg 1 "failed to disable '$svc'"
+					ret=1
+				fi
+				;;
+			*)
+				rmsg 2 "unknown command: $cmd" >&2
+				return 2
+				;;
+		esac
 	done
+
+	rmsg "$ret" "[$progname $cmd $*], exit code: $ret"
+	return "$ret"
 }
 
-# handle the enable subcommand
-do_enable() {
+# handle the link and unlink subcommands
+do_link_unlink() {
+	local cmd=$1
+	local svc
+	local ret=0
+	local file
+	shift
+
 	if (($# < 1)); then
-		rmsg -1 "Argument expected for 'sv enable'"
+		rmsg -1 "Argument expected for '$cmd'"
 		return 1
 	fi
 
+	# Loop all arguments as services
+	msg "Running $progname $cmd $*"
+
 	for svc in "$@"; do
-		cmd="ln -sv $SVCFG/$svc $SVDIR"
-		msg "Running $cmd"
-		$cmd
-		local ret=$?
-		rmsg "$ret" "[$cmd], exit code: $ret"
+		case "$cmd" in
+			link)
+				verbose "link '$svc': ln -sv '$SVCFG/$svc' '$SVDIR'"
+				if ! ln -sv "$SVCFG/$svc" "$SVDIR"; then
+					rmsg 1 "failed to link '$svc'"
+					ret=1
+				fi
+				;;
+			unlink)
+				verbose "unlink '$svc': rm -f '$SVDIR/$svc'"
+				if ! rm -fv "$SVDIR/$svc"; then
+					rmsg 1 "failed to unlink '$svc'"
+					ret=1
+				fi
+				;;
+			*)
+				rmsg 2 "unknown command: $cmd" >&2
+				return 2
+				;;
+		esac
 	done
+
+	rmsg "$ret" "[$progname $cmd $*], exit code: $ret"
+	return "$ret"
 }
 
 # handle any other subcommand
@@ -452,13 +546,14 @@ do_sv_cmd() {
 	return "$ret"
 }
 
+colors_set=false
 tree=false
 log=false
 do_usage=-1
 verbosity=0
 while getopts 'c:d:hltuvV' option; do
 	case "$option" in
-		c) setcolors "$OPTARG";;
+		c) setcolors "$OPTARG"; colors_set=true;;
 		d) SVDIR=$OPTARG;;
 		h) do_usage=0;;
 		l) log=true; cmd='status';;
@@ -471,7 +566,7 @@ while getopts 'c:d:hltuvV' option; do
 done
 shift "$((OPTIND - 1))"
 
-$_colorsSet || setcolors auto
+$colors_set || setcolors auto
 
 # we wait until the colors are optionally set to output the usage message
 if ((do_usage > -1)); then
@@ -492,11 +587,11 @@ case "$cmd" in
 	status)
 		do_status "$@"
 		;;
-	disable)
-		do_disable "$@"
+	link|unlink)
+		do_link_unlink "$cmd" "$@"
 		;;
-	enable)
-		do_enable "$@"
+	enable|disable)
+		do_enable_disable "$cmd" "$@"
 		;;
 	*)
 		if $tree; then
